package com.example.complaintportal.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF005394)
val OnPrimary = Color(0xFFffffff)
val PrimaryContainer = Color(0xFF2b6cb0)
val OnPrimaryContainer = Color(0xFFe1ecff)
val Secondary = Color(0xFF006d40)
val OnSecondary = Color(0xFFffffff)
val SecondaryContainer = Color(0xFF8ef5b5)
val OnSecondaryContainer = Color(0xFF007243)
val Tertiary = Color(0xFF784600)
val OnTertiary = Color(0xFFffffff)
val TertiaryContainer = Color(0xFF9a5b00)
val OnTertiaryContainer = Color(0xFFffe7d2)
val Error = Color(0xFFba1a1a)
val OnError = Color(0xFFffffff)
val ErrorContainer = Color(0xFFffdad6)
val OnErrorContainer = Color(0xFF93000a)
val Background = Color(0xFFf7fafc)
val OnBackground = Color(0xFF181c1e)
val Surface = Color(0xFFf7fafc)
val OnSurface = Color(0xFF181c1e)
val SurfaceVariant = Color(0xFFe0e3e5)
val OnSurfaceVariant = Color(0xFF414750)
val Outline = Color(0xFF727782)
val OutlineVariant = Color(0xFFc1c7d2)
val SurfaceContainerLowest = Color(0xFFffffff)
val SurfaceContainerLow = Color(0xFFf1f4f6)
val SurfaceContainer = Color(0xFFebeef0)
val SurfaceContainerHigh = Color(0xFFe5e9eb)
val SurfaceContainerHighest = Color(0xFFe0e3e5)